### ISSUE TITLE
ws.fetch("position") returns buy and sell side data when short

### ISSUE THREAD

**Issue by kitt-th** [verata-veritatis/pybit#18] opened 2021-01-05 19:45 UTC
Hello,

Firstly thanks for pybit, I'm building code around it nicely, but I have one area of confusion when getting position data via the websocket.

During tests, I had the bot enter 20 contracts long and then 40 contracts short to have the position be short/sell side.
However, ws.fetch("position") returned data for both the Buy and Sell sides of 20 contracts each. Is there something I'm missing? This doesn't reflect the actual position of the account at that time, which should only have data for the Sell side?
Here is the result of a fetch on the (BTCUSD) position so you can see what I mean. 

`

    'Buy': 
        {'user_id': 11111, 'symbol': 'BTCUSD', 'size': 20, 'side': 'Buy', 'position_value': '0.00059908', 
        'entry_price': '33384.52293517', 'liq_price': '16734.5', 'bust_price': '16692.5', 'leverage': '1', 'order_margin': '0', 'position_margin': '0.00059908', 
        'available_balance': '1.59463741', 'take_profit': '0', 'stop_loss': '0', 'realised_pnl': '0.000002', 'trailing_stop': '0', 'trailing_active': '0', 
        'wallet_balance': '1.59523739', 'risk_id': 1, 'occ_closing_fee': '0.0000009', 'occ_funding_fee': '0', 'auto_add_margin': 0, 
        'cum_realised_pnl': '0.00013621', 'position_status': 'Normal', 'position_seq': 0, 'Isolated': True, 'mode': 0, 'position_idx': 0
        }, 

    'Sell': 
        {'user_id': 11111, 'symbol': 'BTCUSD', 'size': 20, 'side': 'Sell', 'position_value': '0.00059725', 'entry_price': '33486.81456676', 
        'liq_price': '999999', 'bust_price': '999999', 'leverage': '1', 'order_margin': '0', 'position_margin': '0.00059723', 'available_balance': '1.59464108', 
        'take_profit': '0', 'stop_loss': '0', 'realised_pnl': '0.00000294', 'trailing_stop': '0', 'trailing_active': '0', 'wallet_balance': '1.59523833', 
        'risk_id': 1, 'occ_closing_fee': '0.00000002', 'occ_funding_fee': '0', 'auto_add_margin': 0, 'cum_realised_pnl': '0.00013715', 'position_status': 'Normal', 
        'position_seq': 0, 'Isolated': True, 'mode': 0, 'position_idx': 0
        }
`

Any help / pointers as to why the data returned does not only have the "Sell" side information gladly received!

**Comment by verata-veritatis** [comment] 2021-01-05 22:50
Hey there!

It's not possible to have multiple positions open on the same inverse perpetual ticker on Bybit. You are essentially altering a single position by adding or subtracting contracts. Also remember that this endpoint shows your position, and not your orders. 

1. You market long 20 contracts. 
2. Your position is now long 20 contracts (0 + 20 = 20).
3. You market short with 40 contracts. 
4. Your position of long 20 contracts is closed, and...
5. You open a short position of 20 contracts (20 - 40 = -20).

Therefore, the endpoint will say that you were 20 contracts long, then 20 contracts short. I believe you're looking for the `order` or `execution` endpoints if you need to see the orders being executed.

**Comment by verata-veritatis** [comment] 2021-01-05 22:54
Ah, I think I understand. I'm assuming it's because the endpoint is showing your historical (previous) position. How it should be behaving is only showing your current endpoint but it seems like the dictionary is not being deleted between updates. Let me take a look. Thanks for bringing this up!

**Comment by verata-veritatis** [comment] 2021-01-06 02:18
@kitt-th Can you please install the next release candidate with `pip` and attempt to run your bot again to see if the behavior is as intended?

This can be done with:
`pip install --upgrade --pre pybit`

**Comment by APF20** [comment] 2021-01-06 07:05
It appears Bybit has just changed the websocket inverse position feed data for the 'side' parameter without telling anybody or updating the changelog/docs.

Previously inverse positions returned 'side': 'None' (string), while linear returned 'side': 'Buy' or 'Sell'.

Now inverse also return a 'Buy' or 'Sell' side parameter, except 'BTCUSDH21', which still returns 'None' (and strangely this ticker position is returned in the websocket data at present, even when no trading is done on it).

**Comment by verata-veritatis** [comment] 2021-01-06 08:26
> It appears Bybit has just changed the websocket inverse position feed data for the 'side' parameter without telling anybody or updating the changelog/docs.
> 
> Previously inverse positions returned 'side': 'None' (string), while linear returned 'side': 'Buy' or 'Sell'.
> 
> Now inverse also return a 'Buy' or 'Sell' side parameter, except 'BTCUSDH21', which still returns 'None' (and strangely this ticker position is returned in the websocket data at present, even when no trading is done on it).

Haha they like doing that. I did a lazy patch tonight assuming that this new way will differentiate between inverse/linear, but I'll take a deeper look tomorrow and make a solid fix.

**Comment by kitt-th** [comment] 2021-01-06 09:30
Thanks for looking into this! I'm going to submit a request to bybit to up their API documentation and notification game. This happens a lot eh. As problematic as Bitmex was with overload, otherwise I found their API to be much better :D in terms of operation.

A REST rq for position still returns "side": "None" but the ws behaves differently. Their data delivery is kinda messy. 
e.g via REST 'is_isolated': True and via ws 'Isolated': True - different key names. smh

**Comment by verata-veritatis** [comment] 2021-01-06 09:33
> Thanks for looking into this! I'm going to submit a request to bybit to up their API documentation and notification game. This happens a lot eh. As problematic as Bitmex was with overload, otherwise I found their API to be much better :D in terms of operation.
> 
> A REST rq for position still returns "side": "None" but the ws behaves differently. Their data delivery is kinda messy.
> e.g via REST 'is_isolated': True and via ws 'Isolated': True - different key names. smh

Yeah it seems like Bybit has no development process, or at least, very little of it. They just throw in experimental updates without referencing documentation and hope it solves things lol. @kitt-th if you're on the API Telegram group, PM Dexter. He's the direct connection between the consumer and the higher-ups of the developers.

**Comment by APF20** [comment] 2021-01-07 08:09
> Haha they like doing that. I did a lazy patch tonight assuming that this new way will differentiate between inverse/linear, but I'll take a deeper look tomorrow and make a solid fix.

The change to use the 'symbol' parameter for the 'if' condition in the patch works well, I checked the fix against both linear and inverse positions and have also asked Bybit to confirm the change on their end is permanent (still waiting on a reply but i assume it would be).

I think the current positions dictionary format is also good as is, with inverse containing a single entry and linear containing multiple entries in the ticker -> side -> data format.

Using 'USDT' to differentiate between inverse/linear is also consistent with the way the REST functions differentiate and overcomes the ongoing issue with 'BTCUSDH21' (and maybe other new futures) still returning 'None' as a side parameter.

I would vote this main issue is resolved 👍 (as for Bybit practices issue, well, we can only hope... haha)

**Comment by dextertd** [comment] 2021-01-07 14:00
Hi chaps, don't want to completely derail this issue but I thought a response was necessary for your detailed comments and criticism of the bybit API. I'm only reading this issue personally as a user of `pybit` but I thought an "official" response as an employee of bybit would be appropriate.

The team have been compiling a list of inconsistencies and other difficulties developers have faced. I can assure you that we are aware of these problems and preparations are being made to shore up the API by removing these inconsistencies. By all means please use my contact info below if you would like to report any to me.

Regarding the deployment of the new inverse future, it's only on testnet so we don't have any documentation for it yet. But once it's on mainnet that will be available!

Again, I didn't want to derail this issue so please feel free to reply in the [Telegram Bybit API Discussion](https://t.me/BybitAPI) or contact [me privately on Telegram](https://t.me/Dexter2).

Thanks.

**Comment by verata-veritatis** [comment] 2021-01-07 18:08
> Hi chaps, don't want to completely derail this issue but I thought a response was necessary for your detailed comments and criticism of the bybit API. I'm only reading this issue personally as a user of `pybit` but I thought an "official" response as an employee of bybit would be appropriate.
> 
> The team have been compiling a list of inconsistencies and other difficulties developers have faced. I can assure you that we are aware of these problems and preparations are being made to shore up the API by removing these inconsistencies. By all means please use my contact info below if you would like to report any to me.
> 
> Regarding the deployment of the new inverse future, it's only on testnet so we don't have any documentation for it yet. But once it's on mainnet that will be available!
> 
> Again, I didn't want to derail this issue so please feel free to reply in the [Telegram Bybit API Discussion](https://t.me/BybitAPI) or contact [me privately on Telegram](https://t.me/Dexter2).
> 
> Thanks.

Hey Dexter—first off, I wanna thank you for stopping by. You've been nothing but extremely helpful in the development of this library and other applications using Bybit's API, as well as in taking recommendations for improvements to the API!

I think all we developers ask for is consistent and accurate documentation of upcoming changes to the API so we know what we need to change and when. There have been a couple moments where I've had to emergency patch `pybit` due to changes in response formats or varying parameters, and I just want to be sure that I can make those changes in a timely manner without having users' bots breaking :)

**Comment by verata-veritatis** [comment] 2021-01-07 18:12
> > Haha they like doing that. I did a lazy patch tonight assuming that this new way will differentiate between inverse/linear, but I'll take a deeper look tomorrow and make a solid fix.
> 
> The change to use the 'symbol' parameter for the 'if' condition in the patch works well, I checked the fix against both linear and inverse positions and have also asked Bybit to confirm the change on their end is permanent (still waiting on a reply but i assume it would be).
> 
> I think the current positions dictionary format is also good as is, with inverse containing a single entry and linear containing multiple entries in the ticker -> side -> data format.
> 
> Using 'USDT' to differentiate between inverse/linear is also consistent with the way the REST functions differentiate and overcomes the ongoing issue with 'BTCUSDH21' (and maybe other new futures) still returning 'None' as a side parameter.
> 
> I would vote this main issue is resolved 👍 (as for Bybit practices issue, well, we can only hope... haha)

Awesome; thanks for checking in on it. I still want to do a couple more tests later today with the change, but I'll push it to release afterwards.

**Comment by kitt-th** [comment] 2021-01-07 21:03
thanks to all the speedy fix-ups here. I've runs successful tests on the testnet BTCUSD inv perp in all combinations and has been smooth. 

I second the request to the devs to supply timely notifications and updated documentation!
After all, happy bot developers stay on bybit generating more fees for the exchange, right?

**Comment by verata-veritatis** [comment] 2021-01-07 21:54
Issue fixed with: ea5375e672a0f6f6c92b9600832f2187a7e4508e

**Closed as completed by verata-veritatis** 2021-01-07 21:54 UTC
